#!/usr/bin/env python3
"""Table abstraction engine and savefile table registry."""
from .cities import CITIES_TABLE, CITY, CITY_RECORD, scrape_cities
from .contracts import (
    CONTRACT,
    CONTRACT_DETAIL,
    CONTRACT_RECORD,
    CONTRACT_STATUS,
    CONTRACT_STRIDE,
    CONTRACT_TABLE,
    LOAN_STATUS,
    contracts_table_spans,
    locate_contracts,
    scrape_contract_status,
    scrape_contracts,
)
from .currencies import (
    CURRENCIES_TABLE,
    CURRENCY_HEAD,
    CURRENCY_TAIL,
    scrape_currencies,
)
from .engine import (
    TableDef,
    table_spans,
    walk_table,
)
from .languages import (
    LANGUAGES_TABLE,
    LANGUAGE_HEAD,
    LANGUAGE_TAIL,
    languages_table_spans,
    locate_languages,
    scrape_languages,
)
from .match_slots import (
    MATCH_SLOTS_TABLE,
    NO_CLUB as MATCH_SLOT_NO_CLUB,
    SLOT as MATCH_SLOT,
    STRIDE as MATCH_SLOT_STRIDE,
    locate_match_slots,
    match_slots_table_spans,
    scrape as scrape_match_slots,
)
from .names import (
    FIRST_NAMES_TABLE,
    NAME_ID_ENTRY,
    NAME_ID_STRIDE,
    NICKNAMES_TABLE,
    SURNAMES_TABLE,
    chain_id_tables,
    discover_id_tables,
    locate_first_names,
    locate_name_tables,
    locate_nicknames,
    locate_surnames,
    walk_browse,
    walk_browse_bounds,
)
from .nations import (
    NATION_HEAD,
    NATION_TAIL,
    NATIONS_TABLE,
    locate_nations,
    nations_table_spans,
    scrape_nations,
)
from .officials import OFFICIAL, OFFICIAL_STRIDE, OFFICIALS_TABLE, scrape_officials
from .person_info import (
    DOB_YEAR_HI,
    DOB_YEAR_LO,
    INFO_HEAD,
    INFO_LAYOUT,
    NAME_ID_MAX,
    NO_CLUB,
    NO_NICKNAME,
    PERSONALITY,
    PERSON_FIELDS,
    PERSON_INFO,
    locate_person_info,
    person_info_table_spans,
    scrape_person_info,
    scrape_players,
)
from .player_attributes import (
    PLAYER_ATTRIBUTES_TABLE,
    locate_player_attributes,
    record_for,
    scrape_player_attributes,
)
from .rounds import (
    ROUND_HEAD,
    ROUND_TRAILER,
    ROUND_TRAILER_WIDTH,
    ROUNDS_TABLE,
    round_names_map,
    scrape_rounds,
)
from .stadiums import (
    STADIUM_HEAD,
    STADIUM_HEADER,
    STADIUMS_TABLE,
    locate_stadiums,
    scrape_stadiums,
)
from .staff import (
    FORMATION_SLOTS,
    HIDDEN_OFFSETS,
    STAFF,
    STAFF_ATTRS,
    STAFF_FIELDS,
    STAFF_FORMATION_SLOTS,
    STAFF_GRID_STRIDE,
    STAFF_HIDDEN_OFFSETS,
    STAFF_STRIDE,
    STAFF_TABLE,
    formation_catalog,
    reputation_tier,
    scrape_staff_attributes,
    style,
)

TABLES = {
    "cities": CITIES_TABLE,
    "contracts": CONTRACT_TABLE,
    "currencies": CURRENCIES_TABLE,
    "first_names": FIRST_NAMES_TABLE,
    "languages": LANGUAGES_TABLE,
    "match_officials": OFFICIALS_TABLE,
    "match_slots": MATCH_SLOTS_TABLE,
    "nations": NATIONS_TABLE,
    "nicknames": NICKNAMES_TABLE,
    "person_info": PERSON_INFO,
    "player_attributes": PLAYER_ATTRIBUTES_TABLE,
    "round_names": ROUNDS_TABLE,
    "stadiums": STADIUMS_TABLE,
    "staff": STAFF_TABLE,
    "surnames": SURNAMES_TABLE,
}

__all__ = [
    # Engine
    "TableDef",
    "table_spans",
    "walk_table",
    "TABLES",
    # Cities
    "CITIES_TABLE",
    "CITY",
    "CITY_RECORD",
    "scrape_cities",
    # Contracts
    "CONTRACT",
    "CONTRACT_DETAIL",
    "CONTRACT_RECORD",
    "CONTRACT_STATUS",
    "CONTRACT_STRIDE",
    "CONTRACT_TABLE",
    "LOAN_STATUS",
    "contracts_table_spans",
    "locate_contracts",
    "scrape_contract_status",
    "scrape_contracts",
    # Currencies
    "CURRENCIES_TABLE",
    "CURRENCY_HEAD",
    "CURRENCY_TAIL",
    "scrape_currencies",
    # Languages
    "LANGUAGES_TABLE",
    "LANGUAGE_HEAD",
    "LANGUAGE_TAIL",
    "languages_table_spans",
    "locate_languages",
    "scrape_languages",
    # Match Slots
    "MATCH_SLOTS_TABLE",
    "MATCH_SLOT",
    "MATCH_SLOT_NO_CLUB",
    "MATCH_SLOT_STRIDE",
    "locate_match_slots",
    "match_slots_table_spans",
    "scrape_match_slots",
    # Names
    "FIRST_NAMES_TABLE",
    "NAME_ID_ENTRY",
    "NAME_ID_STRIDE",
    "NICKNAMES_TABLE",
    "SURNAMES_TABLE",
    "chain_id_tables",
    "discover_id_tables",
    "locate_first_names",
    "locate_name_tables",
    "locate_nicknames",
    "locate_surnames",
    "walk_browse",
    "walk_browse_bounds",
    # Nations
    "NATION_HEAD",
    "NATION_TAIL",
    "NATIONS_TABLE",
    "locate_nations",
    "nations_table_spans",
    "scrape_nations",
    # Officials
    "OFFICIAL",
    "OFFICIAL_STRIDE",
    "OFFICIALS_TABLE",
    "scrape_officials",
    # Person Info
    "DOB_YEAR_HI",
    "DOB_YEAR_LO",
    "INFO_HEAD",
    "INFO_LAYOUT",
    "NAME_ID_MAX",
    "NO_CLUB",
    "NO_NICKNAME",
    "PERSONALITY",
    "PERSON_FIELDS",
    "PERSON_INFO",
    "locate_person_info",
    "person_info_table_spans",
    "scrape_person_info",
    "scrape_players",
    # Player Attributes
    "PLAYER_ATTRIBUTES_TABLE",
    "locate_player_attributes",
    "record_for",
    "scrape_player_attributes",
    # Rounds
    "ROUND_HEAD",
    "ROUND_TRAILER",
    "ROUND_TRAILER_WIDTH",
    "ROUNDS_TABLE",
    "round_names_map",
    "scrape_rounds",
    # Stadiums
    "STADIUM_HEAD",
    "STADIUM_HEADER",
    "STADIUMS_TABLE",
    "locate_stadiums",
    "scrape_stadiums",
    # Staff
    "FORMATION_SLOTS",
    "HIDDEN_OFFSETS",
    "STAFF",
    "STAFF_ATTRS",
    "STAFF_FIELDS",
    "STAFF_FORMATION_SLOTS",
    "STAFF_GRID_STRIDE",
    "STAFF_HIDDEN_OFFSETS",
    "STAFF_STRIDE",
    "STAFF_TABLE",
    "formation_catalog",
    "reputation_tier",
    "scrape_staff_attributes",
    "style",
]
