#!/usr/bin/env python3
"""The savefile table registry: every table definition, by name (`TABLES`). The engine is
`fmparser/core/table.py`."""
from .cities import CITIES_TABLE, CITY, CITY_RECORD, scrape_cities
from .clubs import CLUB_TABLE, club_details, locate_clubs, scrape_clubs
from .competitions import COMP_TABLE, comp_refs, locate_competitions, scrape_competitions
from .contracts import (
    CONTRACT,
    CONTRACT_DETAIL,
    CONTRACT_RECORD,
    CONTRACT_STATUS,
    CONTRACT_STRIDE,
    CONTRACT_TABLE,
    LOAN_STATUS,
    contracts_table_spans,
    locate_contracts,
    scrape_contract_status,
    scrape_contracts,
)
from .comp_rules import (
    COMP_RULES_TABLE,
    HEADER as COMP_RULES_HEADER,
    competition_rounds,
    locate_comp_rules,
    scrape as scrape_comp_rules,
    stage_rows as comp_rule_stage_rows,
)
from .rule_files import (
    RULE_FILES_TABLE,
    locate_rule_files,
    team_counts as rule_file_team_counts,
)
from .currencies import (
    CURRENCIES_TABLE,
    CURRENCY_HEAD,
    CURRENCY_TAIL,
    scrape_currencies,
)
from .fixtures import (
    DAY_BASE as FIXTURE_DAY_BASE,
    DAY_MASK as FIXTURE_DAY_MASK,
    FIXTURE,
    FIXTURES_TABLE,
    MEMBER as FIXTURES_MEMBER,
    MEMBER_HEADER as FIXTURES_MEMBER_HEADER,
    NO_ROUND as FIXTURE_NO_ROUND,
    OPENER as FIXTURE_OPENER,
    STRIDE as FIXTURE_STRIDE,
    fixtures as extract_world_fixtures,
    locate_fixtures,
    read_fixture,
    scrape as scrape_fixtures,
    segments as fixture_segments,
    summary as fixtures_summary,
)
from .comp_stages import (
    COMP_STAGES_TABLE,
    HEADER as COMP_STAGES_HEADER,
    HEADER_STRIDE as COMP_STAGES_HEADER_STRIDE,
    STAGE as COMP_STAGE,
    STRIDE as COMP_STAGE_STRIDE,
    header as comp_stages_header,
    locate_comp_stages,
    read_stage as read_comp_stage,
    scrape as scrape_comp_stages,
    stages as extract_comp_stages,
)
from .comp_honours import (
    COMP_HONOURS_TABLE,
    HONOUR as COMP_HONOUR,
    OPENER as COMP_HONOUR_OPENER,
    STRIDE as COMP_HONOUR_STRIDE,
    honours as extract_comp_honours,
    locate_comp_honours,
    read_honour as read_comp_honour,
    scrape as scrape_comp_honours,
)
from .languages import (
    LANGUAGES_TABLE,
    LANGUAGE_HEAD,
    LANGUAGE_TAIL,
    languages_table_spans,
    locate_languages,
    scrape_languages,
)
from .match_slots import (
    MATCH_SLOTS_TABLE,
    NO_CLUB as MATCH_SLOT_NO_CLUB,
    SLOT as MATCH_SLOT,
    STRIDE as MATCH_SLOT_STRIDE,
    locate_match_slots,
    match_slots_table_spans,
    scrape as scrape_match_slots,
)
from .names import (
    FIRST_NAMES_TABLE,
    NAME_ID_ENTRY,
    NAME_ID_STRIDE,
    NICKNAMES_TABLE,
    SURNAMES_TABLE,
    chain_id_tables,
    discover_id_tables,
    locate_first_names,
    locate_name_tables,
    locate_nicknames,
    locate_surnames,
    walk_browse,
    walk_browse_bounds,
)
from .nations import (
    NATION_HEAD,
    NATION_TAIL,
    NATIONS_TABLE,
    locate_nations,
    nations_table_spans,
    scrape_nations,
)
from .officials import OFFICIAL, OFFICIAL_STRIDE, OFFICIALS_TABLE, scrape_officials
from .person_info import (
    DOB_YEAR_HI,
    DOB_YEAR_LO,
    INFO_HEAD,
    INFO_LAYOUT,
    NAME_ID_MAX,
    NO_CLUB,
    NO_NICKNAME,
    PERSONALITY,
    PERSON_FIELDS,
    PERSON_INFO,
    PERSON_INFO_TABLE,
    locate_person_info,
    person_info_table_spans,
    scrape_person_info,
    scrape_players,
)
from .player_attributes import (
    PLAYER_ATTRIBUTES_TABLE,
    locate_player_attributes,
    record_for,
    scrape_player_attributes,
)
from .rounds import (
    ROUND_HEAD,
    ROUND_TRAILER,
    ROUND_TRAILER_WIDTH,
    ROUNDS_TABLE,
    round_names_map,
    scrape_rounds,
)
from .stadiums import (
    STADIUM_HEAD,
    STADIUM_HEADER,
    STADIUMS_TABLE,
    locate_stadiums,
    scrape_stadiums,
)
from .staff import (
    FORMATION_SLOTS,
    HIDDEN_OFFSETS,
    STAFF,
    STAFF_ATTRS,
    STAFF_FIELDS,
    STAFF_FORMATION_SLOTS,
    STAFF_GRID_STRIDE,
    STAFF_HIDDEN_OFFSETS,
    STAFF_STRIDE,
    STAFF_TABLE,
    formation_catalog,
    reputation_tier,
    scrape_staff_attributes,
    style,
)

TABLES = {
    "cities": CITIES_TABLE,
    "clubs": CLUB_TABLE,
    "competitions": COMP_TABLE,
    "comp_honours": COMP_HONOURS_TABLE,
    "comp_rules": COMP_RULES_TABLE,
    "rule_files": RULE_FILES_TABLE,
    "comp_stages": COMP_STAGES_TABLE,
    "contracts": CONTRACT_TABLE,
    "currencies": CURRENCIES_TABLE,
    "first_names": FIRST_NAMES_TABLE,
    "fixtures": FIXTURES_TABLE,
    "languages": LANGUAGES_TABLE,
    "match_officials": OFFICIALS_TABLE,
    "match_slots": MATCH_SLOTS_TABLE,
    "nations": NATIONS_TABLE,
    "nicknames": NICKNAMES_TABLE,
    "person_info": PERSON_INFO_TABLE,
    "player_attributes": PLAYER_ATTRIBUTES_TABLE,
    "round_names": ROUNDS_TABLE,
    "stadiums": STADIUMS_TABLE,
    "staff": STAFF_TABLE,
    "surnames": SURNAMES_TABLE,
}

__all__ = [
    # Engine
    "TABLES",
    # Cities
    "CITIES_TABLE",
    "CITY",
    "CITY_RECORD",
    "scrape_cities",
    # Clubs and competitions
    "CLUB_TABLE",
    "COMP_TABLE",
    "club_details",
    "comp_refs",
    "locate_clubs",
    "locate_competitions",
    "scrape_clubs",
    "scrape_competitions",
    # Competition rules (archive comp_<uid>.dat)
    "COMP_RULES_HEADER",
    "COMP_RULES_TABLE",
    "comp_rule_stage_rows",
    "competition_rounds",
    "locate_comp_rules",
    "scrape_comp_rules",
    # Rule files (the tagged data dictionary)
    "RULE_FILES_TABLE",
    "locate_rule_files",
    "rule_file_team_counts",
    # Contracts
    "CONTRACT",
    "CONTRACT_DETAIL",
    "CONTRACT_RECORD",
    "CONTRACT_STATUS",
    "CONTRACT_STRIDE",
    "CONTRACT_TABLE",
    "LOAN_STATUS",
    "contracts_table_spans",
    "locate_contracts",
    "scrape_contract_status",
    "scrape_contracts",
    # Currencies
    "CURRENCIES_TABLE",
    "CURRENCY_HEAD",
    "CURRENCY_TAIL",
    "scrape_currencies",
    # Languages
    "LANGUAGES_TABLE",
    "LANGUAGE_HEAD",
    "LANGUAGE_TAIL",
    "languages_table_spans",
    "locate_languages",
    "scrape_languages",
    # Match Slots
    "MATCH_SLOTS_TABLE",
    "MATCH_SLOT",
    "MATCH_SLOT_NO_CLUB",
    "MATCH_SLOT_STRIDE",
    "locate_match_slots",
    "match_slots_table_spans",
    "scrape_match_slots",
    # Names
    "FIRST_NAMES_TABLE",
    "NAME_ID_ENTRY",
    "NAME_ID_STRIDE",
    "NICKNAMES_TABLE",
    "SURNAMES_TABLE",
    "chain_id_tables",
    "discover_id_tables",
    "locate_first_names",
    "locate_name_tables",
    "locate_nicknames",
    "locate_surnames",
    "walk_browse",
    "walk_browse_bounds",
    # Nations
    "NATION_HEAD",
    "NATION_TAIL",
    "NATIONS_TABLE",
    "locate_nations",
    "nations_table_spans",
    "scrape_nations",
    # Officials
    "OFFICIAL",
    "OFFICIAL_STRIDE",
    "OFFICIALS_TABLE",
    "scrape_officials",
    # Person Info
    "DOB_YEAR_HI",
    "DOB_YEAR_LO",
    "INFO_HEAD",
    "INFO_LAYOUT",
    "NAME_ID_MAX",
    "NO_CLUB",
    "NO_NICKNAME",
    "PERSONALITY",
    "PERSON_FIELDS",
    "PERSON_INFO",
    "PERSON_INFO_TABLE",
    "locate_person_info",
    "person_info_table_spans",
    "scrape_person_info",
    "scrape_players",
    # Player Attributes
    "PLAYER_ATTRIBUTES_TABLE",
    "locate_player_attributes",
    "record_for",
    "scrape_player_attributes",
    # Rounds
    "ROUND_HEAD",
    "ROUND_TRAILER",
    "ROUND_TRAILER_WIDTH",
    "ROUNDS_TABLE",
    "round_names_map",
    "scrape_rounds",
    # Stadiums
    "STADIUM_HEAD",
    "STADIUM_HEADER",
    "STADIUMS_TABLE",
    "locate_stadiums",
    "scrape_stadiums",
    # Staff
    "FORMATION_SLOTS",
    "HIDDEN_OFFSETS",
    "STAFF",
    "STAFF_ATTRS",
    "STAFF_FIELDS",
    "STAFF_FORMATION_SLOTS",
    "STAFF_GRID_STRIDE",
    "STAFF_HIDDEN_OFFSETS",
    "STAFF_STRIDE",
    "STAFF_TABLE",
    "formation_catalog",
    "reputation_tier",
    "scrape_staff_attributes",
    "style",
]
